export const TOPIC_CATEGORIES = [
  "everyday",
  "personal",
  "opinions",
  "society",
  "technology",
  "work",
  "communication",
  "relationships",
  "travel",
  "creativity",
  "hypothetical",
  "situational",
  "fun",
] as const;

export type TopicCategory = (typeof TOPIC_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<TopicCategory, string> = {
  everyday: "Everyday Life",
  personal: "Personal",
  opinions: "Opinions",
  society: "Society",
  technology: "Technology",
  work: "Work & Career",
  communication: "Communication",
  relationships: "Relationships",
  travel: "Travel & Culture",
  creativity: "Creativity",
  hypothetical: "Hypothetical",
  situational: "Situational",
  fun: "Fun & Random",
};

export const TOPIC_DIFFICULTIES = ["easy", "medium", "challenge"] as const;

export type TopicDifficulty = (typeof TOPIC_DIFFICULTIES)[number];

export const DIFFICULTY_LABELS: Record<TopicDifficulty, string> = {
  easy: "Easy",
  medium: "Medium",
  challenge: "Challenge",
};

export interface Topic {
  id: string;
  prompt: string;
  category: TopicCategory;
  difficulty: TopicDifficulty;
}

export const TOPICS: Topic[] = [
  // Everyday Life
  {
    id: "everyday-morning-routine",
    prompt: "Describe your typical morning from waking up to leaving the house.",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-favorite-meal",
    prompt: "Describe a typical meal you cook and walk through how you make it.",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-small-habit",
    prompt: "What small habit has improved your day-to-day life, and how did you start it?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-ideal-weekend",
    prompt: "Describe your ideal weekend from start to finish.",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-good-day",
    prompt: "What does a good day look like for you, and what makes it good?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-unusual-object",
    prompt: "What is the most unusual thing in your home, and what is its story?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-routine-change",
    prompt: "How has your daily routine changed compared to five years ago?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-regular-place",
    prompt: "Describe a place you visit almost every week and what it is like.",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-schedule-change",
    prompt: "If you could change one thing about your everyday schedule, what would it be and why?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-time-trade",
    prompt: "If you had an extra hour every day, how would you spend it, and why?",
    category: "everyday",
    difficulty: "easy",
  },

  // Personal
  {
    id: "personal-hard-lesson",
    prompt: "What is a lesson you learned the hard way?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-proud-moment",
    prompt: "Describe a moment you felt proud of yourself.",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-changed-belief",
    prompt: "What is something you used to believe that you no longer believe?",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-admired-quality",
    prompt: "What personal quality do you admire most in yourself, and when does it show?",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-changed-mind",
    prompt: "Describe a time you changed your mind about something important.",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-biggest-strength",
    prompt: "What is your biggest strength, and what situation brings it out?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-self-improvement",
    prompt: "What is something you are actively working to improve about yourself?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-useful-mistake",
    prompt: "Describe a mistake that turned out to be useful in the end.",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-comforting-memory",
    prompt: "What memory do you return to when you need comfort?",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-advice-to-younger-self",
    prompt: "If you could give your younger self one piece of advice, what would it be?",
    category: "personal",
    difficulty: "medium",
  },

  // Opinions
  {
    id: "opinions-planning-vs-spontaneity",
    prompt: "Is it better to plan your life carefully or leave room for spontaneity?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-cities-cars-people",
    prompt: "Should cities prioritize cars or people?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-social-media-connection",
    prompt: "Is social media more helpful or harmful for genuine connection?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-technology-dependence",
    prompt: "Are we too dependent on technology in our daily lives?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-school-focus",
    prompt: "Should schools focus more on practical skills or traditional subjects?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-remote-vs-office",
    prompt: "Is remote work better than working in an office?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-money-happiness",
    prompt: "Does money buy happiness? Explain your view.",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-compulsory-voting",
    prompt: "Should voting be compulsory in democratic countries?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-fast-food-responsibility",
    prompt: "Should fast food companies be responsible for public health?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-expert-vs-generalist",
    prompt: "Is it better to be an expert in one thing or know a little about everything?",
    category: "opinions",
    difficulty: "medium",
  },

  // Society
  {
    id: "society-welcoming-communities",
    prompt: "How can communities become more welcoming to newcomers?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-generation-challenge",
    prompt: "What is the biggest challenge facing your generation?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-automation-support",
    prompt: "How should society support people whose jobs disappear because of automation?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-environment-responsibility",
    prompt: "What responsibility do individuals have toward the environment?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-services-efficiency",
    prompt: "Should public services prioritize efficiency or accessibility?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-definition-of-home",
    prompt: "How has the meaning of home changed in recent decades?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-social-media-elections",
    prompt: "What role should social media companies play during elections?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-encourage-volunteering",
    prompt: "How can we encourage more people to volunteer in their communities?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-four-day-week",
    prompt: "Is a four-day work week a realistic future for most countries?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-cities-climate",
    prompt: "How should cities prepare for the effects of climate change?",
    category: "society",
    difficulty: "challenge",
  },

  // Technology
  {
    id: "technology-memory",
    prompt: "How has technology changed the way we remember things?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-month-without-phone",
    prompt: "Could you live a month without a smartphone? How would you manage?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-overreliance",
    prompt: "What technology do you think we rely on too heavily?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-ai-in-education",
    prompt: "How should artificial intelligence be used in education?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-life-in-20-years",
    prompt: "What will everyday life look like in twenty years because of technology?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-privacy-realism",
    prompt: "Is privacy realistic in the digital age?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-better-life",
    prompt: "What is one technology that has genuinely made your life better?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-adoption",
    prompt: "How do you decide which new technologies to adopt?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-instant-everything",
    prompt: "What are the downsides of everything being available instantly?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-children-screens",
    prompt: "Should children have limits on screen time? Why or why not?",
    category: "technology",
    difficulty: "medium",
  },

  // Work & Career
  {
    id: "work-meaningful-job",
    prompt: "What makes a job meaningful to you?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-ideal-workplace",
    prompt: "Describe a workplace that would bring out the best in people.",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-stable-vs-passion",
    prompt: "Is it better to have a stable job or follow your passion?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-difficult-feedback",
    prompt: "How do you handle difficult feedback at work?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-future-skills",
    prompt: "What skills will matter most in the future workplace?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-employee-wellbeing",
    prompt: "Should companies care about their employees' wellbeing, or is profit enough?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-best-boss",
    prompt: "Describe the best boss you could imagine.",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-salary-vs-satisfaction",
    prompt: "How important is salary compared to job satisfaction?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-restart-career",
    prompt: "What would you do differently if you could start your career again?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-motivation-unenjoyable",
    prompt: "How do you stay motivated on a task you do not enjoy?",
    category: "work",
    difficulty: "medium",
  },

  // Communication
  {
    id: "communication-good-listener",
    prompt: "What makes someone a good listener?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-disagreement",
    prompt: "How do you handle disagreements without damaging the relationship?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-clarity-solved",
    prompt: "Describe a time when clear communication solved a problem.",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-truth-vs-peace",
    prompt: "Is it better to say what you think or keep the peace?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-explain-simply",
    prompt: "How do you explain a complex idea in simple terms?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-body-language",
    prompt: "What role does body language play in how we communicate?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-digital-honesty",
    prompt: "How has digital communication changed how honest we are with each other?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-silence",
    prompt: "When is silence more powerful than words?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-feedback",
    prompt: "How do you give feedback that people actually hear?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-memorable-speech",
    prompt: "What makes a speech or presentation memorable?",
    category: "communication",
    difficulty: "medium",
  },

  // Relationships
  {
    id: "relationships-lasting-friendship",
    prompt: "What makes a friendship last for decades?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-long-distance",
    prompt: "How do you maintain relationships when you live far apart?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-trust",
    prompt: "What does trust look like in a relationship?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-support",
    prompt: "Describe a time someone supported you when you really needed it.",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-disagree-often",
    prompt: "Is it healthy to disagree often in a close relationship?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-balance",
    prompt: "How do you balance time with others and time alone?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-partner-quality",
    prompt: "What is the most important quality in a long-term partner?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-change-with-age",
    prompt: "How do relationships change as people grow older?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-friend-let-down",
    prompt: "What would you do if a friend let you down?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-idea-of-friend",
    prompt: "How has your idea of a good friend changed over time?",
    category: "relationships",
    difficulty: "challenge",
  },

  // Travel & Culture
  {
    id: "travel-place-to-visit",
    prompt: "Describe a place you would love to visit and why.",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-teaches-about-self",
    prompt: "What does traveling teach you about yourself?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-alone-vs-together",
    prompt: "Is it better to travel alone or with others?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-culture-tradition",
    prompt: "Describe a tradition from your culture that matters to you.",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-culture-perspective",
    prompt: "How does experiencing another culture change your perspective?",
    category: "travel",
    difficulty: "challenge",
  },
  {
    id: "travel-year-abroad",
    prompt: "What would you pack and plan for a year abroad?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-staying-put",
    prompt: "Is staying in one place underrated compared to traveling?",
    category: "travel",
    difficulty: "challenge",
  },
  {
    id: "travel-cultural-meal",
    prompt: "Describe a meal that represents your culture and its story.",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-language-preparation",
    prompt: "How do you prepare for a trip to a country with a different language?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-experience-once",
    prompt: "What is something everyone should experience at least once in their life?",
    category: "travel",
    difficulty: "medium",
  },

  // Creativity
  {
    id: "creativity-best-ideas",
    prompt: "Where do your best ideas come from?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-ideal-project",
    prompt: "Describe a creative project you would start if nothing could go wrong.",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-learned-vs-born",
    prompt: "Can creativity be learned, or is it a talent you are born with?",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-getting-unstuck",
    prompt: "What helps you get unstuck when you have no ideas?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-constraints",
    prompt: "How do constraints help or hinder creativity?",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-moving-art",
    prompt: "Describe a piece of art, music, or writing that moved you.",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-boredom",
    prompt: "What role does boredom play in creativity?",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-create-anything",
    prompt: "If you could create anything regardless of skill, what would it be?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-capturing-ideas",
    prompt: "How do you capture ideas before you lose them?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-art-as-adults",
    prompt: "Why do some people stop making art as they grow older?",
    category: "creativity",
    difficulty: "challenge",
  },

  // Hypothetical
  {
    id: "hypothetical-superpower",
    prompt: "If you could have any superpower, which would you choose and why?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-time-travel",
    prompt: "If you could travel back in time, where would you go and what would you do?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-one-question",
    prompt: "If you could ask one question to anyone in history, who and what would you ask?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-year-off",
    prompt: "What would you do with a year off and unlimited money?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-master-skill",
    prompt: "If you could instantly master one skill, what would it be and why?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-city-design",
    prompt: "If you could design a city from scratch, what would it be like?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-fictional-world",
    prompt: "If you could live in any fictional world, where would you go?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-one-wish",
    prompt: "What would you change about the world if you had one wish?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-all-languages",
    prompt: "If you could speak every language, how would your life change?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-future-self",
    prompt: "If you met your future self, what would you ask them?",
    category: "hypothetical",
    difficulty: "medium",
  },

  // Situational
  {
    id: "situational-call-to-action",
    prompt: "You have two minutes to convince a group of strangers to support a cause you believe in. What do you say?",
    category: "situational",
    difficulty: "challenge",
  },
  {
    id: "situational-acceptance-speech",
    prompt: "You win a surprise award at a ceremony. Deliver your acceptance speech.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-explain-to-child",
    prompt: "Explain a topic you know well to a ten-year-old.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-lost-without-phone",
    prompt: "You are lost in a new city without your phone. What do you do?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-hobby-pitch",
    prompt: "Convince your audience that a hobby you love is worth trying.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-wedding-toast",
    prompt: "You must give a toast at a wedding. What do you say?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-dream-day-plan",
    prompt: "Describe your dream day to someone who will plan it for you.",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-found-wallet",
    prompt: "You find a wallet with money and an ID. What happens next?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-business-pitch",
    prompt: "Pitch a small business idea to a friend in two minutes.",
    category: "situational",
    difficulty: "challenge",
  },
  {
    id: "situational-introduce-yourself",
    prompt: "You are asked to introduce yourself to a room of strangers. How do you do it?",
    category: "situational",
    difficulty: "medium",
  },

  // Fun & Random
  {
    id: "fun-best-smell",
    prompt: "What is the best smell in the world, and what does it remind you of?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-life-soundtrack",
    prompt: "If your life had a soundtrack, what songs would be on it?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-useless-skill",
    prompt: "What is a useless skill you are secretly proud of?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-funniest-moment",
    prompt: "Describe the funniest thing that has ever happened to you.",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-animal-sidekick",
    prompt: "If you could have any animal as a sidekick, what would it be?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-favorite-season",
    prompt: "What are the best and worst parts of your favorite season?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-dream-home",
    prompt: "What would your dream home look like, inside and out?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-one-meal",
    prompt: "If you had to eat one meal for the rest of your life, what would it be?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-invented-rule",
    prompt: "What is a rule you would invent for everyone to follow?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-strangest-dream",
    prompt: "What is the strangest dream you can remember?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "everyday-sunday",
    prompt: "What does a typical Sunday look like for you?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-grocery-run",
    prompt: "How do you decide what to buy when you go grocery shopping?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-commute",
    prompt: "What do you do during your commute or travel time?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-weather",
    prompt: "How does the weather affect your mood and your plans?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-laundry",
    prompt: "Describe your least favorite household chore and why you dread it.",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-breakfast",
    prompt: "What is your usual breakfast, and what would an ideal one look like?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-small-decisions",
    prompt: "What small decisions do you make every day without really thinking about them?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-neighborhood",
    prompt: "Describe your neighborhood to someone who has never been there.",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-phone-use",
    prompt: "How much time do you spend on your phone in a day, and what is it mostly for?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-waiting",
    prompt: "What do you usually do when you are waiting for something?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-evening-routine",
    prompt: "Walk through how you wind down in the evening before bed.",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-walking",
    prompt: "Describe a walk you take regularly and what you notice along the way.",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-leftovers",
    prompt: "What do you usually do with leftovers from dinner?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-seasons",
    prompt: "How does your life change with each season of the year?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-mail",
    prompt: "What kind of mail do you actually open, and what goes straight to the bin?",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-plant-care",
    prompt: "Do you have any plants? Describe how you care for them.",
    category: "everyday",
    difficulty: "medium",
  },
  {
    id: "everyday-garbage-recycle",
    prompt: "Describe the steps you take when taking out the trash and recycling.",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-keys-phone-wallet",
    prompt: "Do you have a routine for making sure you have your keys, phone, and wallet before leaving?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-extra-sleep",
    prompt: "What would you do on a morning when you could sleep as long as you wanted?",
    category: "everyday",
    difficulty: "easy",
  },
  {
    id: "everyday-closet",
    prompt: "Describe what a typical wardrobe day looks like: how do you pick what to wear?",
    category: "everyday",
    difficulty: "challenge",
  },
  {
    id: "everyday-mundane-joy",
    prompt: "What is a perfectly ordinary moment that consistently makes you happy?",
    category: "everyday",
    difficulty: "challenge",
  },
  {
    id: "everyday-time-use",
    prompt: "If you tracked every minute of a day, where do you think your time would actually go?",
    category: "everyday",
    difficulty: "challenge",
  },
  {
    id: "everyday-food-identity",
    prompt: "In what ways does the food you eat reflect where you grew up or how you live now?",
    category: "everyday",
    difficulty: "challenge",
  },
  {
    id: "everyday-slow-down",
    prompt: "What is something you do slowly on purpose, even though you could do it faster?",
    category: "everyday",
    difficulty: "challenge",
  },
  {
    id: "everyday-last-weeks-log",
    prompt: "Imagine your last week as a newspaper front page. What would the headlines be?",
    category: "everyday",
    difficulty: "challenge",
  },
  {
    id: "personal-overcome",
    prompt: "What is something difficult you overcame, and what helped you get through it?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-future-goal",
    prompt: "Describe a goal you have for the next few years and why it matters to you.",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-fear",
    prompt: "What is something you used to be afraid of and are no longer afraid of?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-defining-value",
    prompt: "Which of your values do you find hardest to actually live by, and why?",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-change",
    prompt: "Describe a time your plans changed unexpectedly and how you adapted.",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-habit-start",
    prompt: "Describe a habit you successfully built and how you managed to stick with it.",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-strong-memory",
    prompt: "What is one memory that feels unusually vivid, and why do you think it stuck?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-comfort-zone",
    prompt: "What is outside your comfort zone but not too far outside it?",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-boundary",
    prompt: "Describe a boundary you have learned to set and what changed when you set it.",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-energy",
    prompt: "What gives you energy, and what quietly drains it?",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-tough-decision",
    prompt: "Walk through a tough decision you made and how you finally chose.",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-self-talk",
    prompt: "What is something you tell yourself when things are not going well?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-growth-5y",
    prompt: "How have you grown as a person in the last five years?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-skill-mastery",
    prompt: "Describe a skill you are proud of and how you developed it.",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-rest",
    prompt: "What does real rest look like for you, as opposed to just not working?",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-patience",
    prompt: "What situation tests your patience the most, and how do you handle it?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-comparison",
    prompt: "How do you keep yourself from comparing your life to other people's?",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-luck",
    prompt: "Do you believe in luck? Describe a lucky moment in your life.",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-gratitude",
    prompt: "What three things are you grateful for this week, and why?",
    category: "personal",
    difficulty: "easy",
  },
  {
    id: "personal-future-self",
    prompt: "What do you hope the version of you ten years from now is grateful for?",
    category: "personal",
    difficulty: "challenge",
  },
  {
    id: "personal-family-influence",
    prompt: "Which habit or belief did you inherit from your family that you are glad about?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "personal-alone",
    prompt: "How do you feel about spending time alone, and what do you do with it?",
    category: "personal",
    difficulty: "medium",
  },
  {
    id: "opinions-overrated",
    prompt: "What popular thing do you think is overrated, and why?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-underrated",
    prompt: "What underrated thing do you think more people should appreciate?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-books-vs-movies",
    prompt: "Is it better to read the book first or watch the movie first?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-remote-work",
    prompt: "What is your honest opinion about remote work vs working in an office?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-manners",
    prompt: "Which modern manners matter most to you, and which old-fashioned ones do you miss?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-screens",
    prompt: "Do screens bring people together or pull them apart? Take a side and defend it.",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-city-country",
    prompt: "Would you rather live in a big city or a small town? Defend your choice.",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-ads",
    prompt: "Do advertisements ever genuinely influence your buying decisions?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-tipping",
    prompt: "What is your opinion on tipping culture?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-reviews",
    prompt: "Do you trust online reviews? Why or why not?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-pets",
    prompt: "Should pets be allowed in more public places?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-minimalism",
    prompt: "Is minimalism a liberating lifestyle or just a trend?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-punctuation-text",
    prompt: "Does ending a text message with a period change how it feels?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-news-consumption",
    prompt: "Should people read the news every day, or is it healthier to limit it?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-food-cost",
    prompt: "Is paying more for high-quality food worth it?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-age-songs",
    prompt: "Do musicians get better with age or was their best work early on?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-noise",
    prompt: "Is silence underrated? Where in your life could you use more of it?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-perfection",
    prompt: "Is it better to ship something imperfect or wait until it is flawless?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-elections-voice",
    prompt: "How much can one vote really change in a democracy?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-gift-giving",
    prompt: "Is giving a thoughtful gift more important than an expensive one?",
    category: "opinions",
    difficulty: "medium",
  },
  {
    id: "opinions-music-taste",
    prompt: "Can you still be friends with someone whose music taste is terrible?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-wake-up",
    prompt: "Should mornings start slowly or should you get straight to work?",
    category: "opinions",
    difficulty: "easy",
  },
  {
    id: "opinions-age-declining",
    prompt: "At what age do people become 'old', and does that definition even make sense?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "opinions-honesty",
    prompt: "Is complete honesty always the best policy in relationships?",
    category: "opinions",
    difficulty: "challenge",
  },
  {
    id: "society-volunteering",
    prompt: "Have you ever volunteered? Describe the experience and how it made you feel.",
    category: "society",
    difficulty: "easy",
  },
  {
    id: "society-community",
    prompt: "What makes a community feel like a community?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-local-business",
    prompt: "Why do some local shops thrive while others close down?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-public-spaces",
    prompt: "Describe a public space you love and what makes it work well.",
    category: "society",
    difficulty: "easy",
  },
  {
    id: "society-waste",
    prompt: "How much do people really think about the waste they produce?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-festivals",
    prompt: "Describe a local festival or tradition and why it matters to the people who celebrate it.",
    category: "society",
    difficulty: "easy",
  },
  {
    id: "society-aging",
    prompt: "How should society prepare for an aging population?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-news-trust",
    prompt: "Where do you get your news, and how much do you trust it?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-immigration",
    prompt: "What are the biggest challenges and benefits of immigration for a society?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-civic-duty",
    prompt: "What does being a good citizen mean to you in everyday life?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-libraries",
    prompt: "Are public libraries still relevant in the digital age?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-education-gap",
    prompt: "How fair is the education system in your country?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-public-transport",
    prompt: "What would make public transport better in your city?",
    category: "society",
    difficulty: "easy",
  },
  {
    id: "society-small-talk-strangers",
    prompt: "How do people in your country behave toward strangers on the street?",
    category: "society",
    difficulty: "easy",
  },
  {
    id: "society-noise-city",
    prompt: "Should cities do more to reduce noise and light pollution?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-traditions-change",
    prompt: "Which tradition in your culture do you think is changing, and is that good or bad?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-housing",
    prompt: "What do you think is the biggest problem with housing in your area?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-role-models",
    prompt: "Who does society hold up as role models, and are they the right people?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-neighbors",
    prompt: "How well do you know your neighbors, and how important is that?",
    category: "society",
    difficulty: "easy",
  },
  {
    id: "society-energy",
    prompt: "What is the most realistic way for your country to reduce its energy consumption?",
    category: "society",
    difficulty: "challenge",
  },
  {
    id: "society-charity",
    prompt: "Is it better to donate money to charities or to help people directly?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-social-clubs",
    prompt: "Do people join fewer clubs and associations today than they used to?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "society-rules",
    prompt: "Which unwritten rules of society do you follow without thinking about them?",
    category: "society",
    difficulty: "medium",
  },
  {
    id: "technology-phone-first",
    prompt: "What is the first thing you do with your phone in the morning?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-ai-daily",
    prompt: "How has artificial intelligence already changed your daily life?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-passwords",
    prompt: "How do you actually manage all your passwords?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-screen-time",
    prompt: "Could you survive a day without any screens? What would that day look like?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-smart-home",
    prompt: "What would a truly smart home do for you, and would you want it?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-old-gadget",
    prompt: "What is a piece of technology you own that has survived for years, and why do you keep it?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-notifications",
    prompt: "Which app notifications do you actually allow, and which do you mute?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-video-calls",
    prompt: "Do video calls feel as real as in-person conversations?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-online-shopping",
    prompt: "How has online shopping changed the way you buy things?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-privacy",
    prompt: "How much privacy are you willing to trade for convenience?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-ebooks",
    prompt: "Ebooks or paper books: which do you prefer and why?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-gaming",
    prompt: "Are video games art, entertainment, or both?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-automation",
    prompt: "Which everyday task would you happily automate?",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-streaming",
    prompt: "Do streaming services make it easier or harder to decide what to watch?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-first-device",
    prompt: "Describe the first electronic device you remember owning.",
    category: "technology",
    difficulty: "easy",
  },
  {
    id: "technology-digital-detox",
    prompt: "Describe your experience, real or imagined, of a digital detox weekend.",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-social-media-use",
    prompt: "How has social media changed how you stay in touch with people?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-search-future",
    prompt: "How do you think people will search for information ten years from now?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-e-waste",
    prompt: "What happens to the devices you no longer use?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-deepfakes",
    prompt: "How much should we worry about fake audio and video online?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-vehicles",
    prompt: "Would you buy an electric car? Why or why not?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-tools-people",
    prompt: "What technology do you think makes people's lives genuinely better?",
    category: "technology",
    difficulty: "challenge",
  },
  {
    id: "technology-cloud-everything",
    prompt: "Is it a good thing that your photos, documents, and files live on the cloud?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "technology-analog",
    prompt: "What analog activity have you kept, or would you like to return to?",
    category: "technology",
    difficulty: "medium",
  },
  {
    id: "work-first-job",
    prompt: "Describe your first job and what it taught you.",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-ideal-day",
    prompt: "What would your ideal workday look like from start to finish?",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-boss",
    prompt: "What makes a good manager, in your experience?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-meetings",
    prompt: "What is wrong with most meetings, and how would you fix them?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-ambition",
    prompt: "How ambitious are you when it comes to your career?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-balance",
    prompt: "How do you protect your time after work hours?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-colleagues",
    prompt: "What makes a coworker a pleasure to work with?",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-monday",
    prompt: "Why do Mondays feel different from other weekdays?",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-career-change",
    prompt: "If you could start a completely different career, what would it be?",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-salary-talk",
    prompt: "Should colleagues be open about how much they earn?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-boring-task",
    prompt: "What is the most boring task at work, and how do you get through it?",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-side-project",
    prompt: "Have you ever had a side project alongside your main work? Describe it.",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-network",
    prompt: "How important is networking for getting ahead at work?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-promotion",
    prompt: "How do you know when it is time to ask for a promotion?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-presentation",
    prompt: "How do you prepare when you have to present something to others?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-feedback",
    prompt: "What is the best feedback you have ever received at work?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-deadline",
    prompt: "Walk through how you handle a tight deadline.",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-burnout",
    prompt: "How can you tell you are close to burning out, and what do you do about it?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-office-culture",
    prompt: "Describe the culture at your workplace and whether it suits you.",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-retirement",
    prompt: "What does a good retirement look like to you?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-satisfaction",
    prompt: "What matters more at work: the pay or the feeling of doing meaningful work?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-first-week",
    prompt: "Describe the experience of starting a new job and learning the ropes.",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "work-interruptions",
    prompt: "What is the most common way your work gets interrupted, and how do you recover?",
    category: "work",
    difficulty: "medium",
  },
  {
    id: "work-future-of-work",
    prompt: "How do you think your job will change in the next decade?",
    category: "work",
    difficulty: "challenge",
  },
  {
    id: "work-teamwork",
    prompt: "Do you work better alone or in a team, and why?",
    category: "work",
    difficulty: "easy",
  },
  {
    id: "communication-small-talk",
    prompt: "How do you keep a small talk conversation going at a party?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-apology",
    prompt: "What makes an apology genuine?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-questions",
    prompt: "What is the best question you have ever been asked in a conversation?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-listening",
    prompt: "How can you tell someone is really listening to you?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-email-tone",
    prompt: "Have you ever misunderstood the tone of a message? What happened?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-saying-no",
    prompt: "Why is it hard to say no, and how do you manage it?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-compliments",
    prompt: "Do you find it easier to give or receive compliments?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-gossip",
    prompt: "Where is the line between sharing news and gossiping?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-argument",
    prompt: "Describe a disagreement that ended well and how it got there.",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-confident-speaker",
    prompt: "Describe someone you know who speaks really well. What do they do differently?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-writing-speaking",
    prompt: "Are you better at expressing yourself in writing or in speech?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-humor",
    prompt: "How much does humor matter in everyday conversation?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-language-learning",
    prompt: "What has been the hardest part of learning another language?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-body-language-reading",
    prompt: "How much do you notice body language when talking to someone?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-negotiation",
    prompt: "Describe a time you negotiated for something and how it went.",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-venting",
    prompt: "When a friend is upset, do they usually want advice or just someone to listen?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-phone-calls",
    prompt: "Do you prefer phone calls or messages? Why?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-group-chats",
    prompt: "What is your role in group chats? Describe the group chat dynamics you know.",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-interrupting",
    prompt: "When is it acceptable to interrupt someone, if ever?",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-clear-message",
    prompt: "Walk through a message that was easy to misunderstand and how it could have been clearer.",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "communication-silence-comfort",
    prompt: "Are you comfortable with silence in a conversation?",
    category: "communication",
    difficulty: "easy",
  },
  {
    id: "communication-crucial-talk",
    prompt: "Describe a conversation you avoided for a long time and why.",
    category: "communication",
    difficulty: "challenge",
  },
  {
    id: "communication-questions-curious",
    prompt: "What question do you wish people would ask you more often?",
    category: "communication",
    difficulty: "medium",
  },
  {
    id: "relationships-close-friend",
    prompt: "Describe your closest friend and what makes that friendship work.",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-making-plans",
    prompt: "Are you usually the one making plans with friends, or is someone else?",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-drift",
    prompt: "Describe a friendship that faded away and why it ended.",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-trust-building",
    prompt: "How is trust built between two people?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-supporting-friend",
    prompt: "How do you support a friend who is going through a hard time?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-forgiveness",
    prompt: "Is forgiving someone the same as letting them off the hook?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-quality-time",
    prompt: "What does quality time with someone you care about look like for you?",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-boundaries-family",
    prompt: "How do you balance family expectations with your own choices?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-celebrating-others",
    prompt: "How do you feel when a friend succeeds at something you also wanted?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-long-distance-friend",
    prompt: "Could you maintain a close friendship or relationship long distance?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-meeting-people",
    prompt: "Where are you most likely to meet new people in your current life?",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-conflict",
    prompt: "Describe a small conflict you had recently and how you handled it.",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-birthdays",
    prompt: "How do you usually celebrate the birthday of someone you care about?",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-love-languages",
    prompt: "How do you show someone you care about them without saying it?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-inlaws",
    prompt: "What makes meeting a partner's family stressful or easy?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-single",
    prompt: "What is the best and worst part about being single?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-reunion",
    prompt: "Imagine meeting an old friend you have not seen in years. Describe the meeting.",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-anniversary",
    prompt: "How would you celebrate an anniversary of a close relationship?",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-asking-help",
    prompt: "Is it easy or hard for you to ask friends for help?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-phone-contact",
    prompt: "How often do you actually contact your family? Describe how you stay in touch.",
    category: "relationships",
    difficulty: "easy",
  },
  {
    id: "relationships-first-impressions",
    prompt: "How accurate are first impressions of people, really?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "relationships-secrets",
    prompt: "When is it okay to keep a secret from a friend?",
    category: "relationships",
    difficulty: "challenge",
  },
  {
    id: "relationships-friend-roles",
    prompt: "What roles do your different friends play in your life?",
    category: "relationships",
    difficulty: "medium",
  },
  {
    id: "travel-favorite-trip",
    prompt: "Describe your favorite trip and what made it special.",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-packing",
    prompt: "What is your packing style, and what can you never forget to bring?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-planning",
    prompt: "Are you a planner or spontaneous traveler? Describe how you plan a trip.",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-solo",
    prompt: "Would you travel alone? Describe what a solo trip of yours might look like.",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-airport",
    prompt: "Describe the airport experience from check-in to takeoff.",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-road-trip",
    prompt: "Describe an ideal road trip: route, companions, and snacks included.",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-local-food",
    prompt: "What local food have you tried that you will never forget?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-souvenirs",
    prompt: "What do you bring back from trips, and what is the best souvenir you ever got?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-language-barrier",
    prompt: "Describe a time language was a barrier while traveling.",
    category: "travel",
    difficulty: "challenge",
  },
  {
    id: "travel-mistake",
    prompt: "Describe a travel mistake you made and what it taught you.",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-bucket-list",
    prompt: "What is at the top of your travel bucket list, and why?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-explore-vs-stay",
    prompt: "When you travel, do you prefer staying in one place or moving around?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-budget",
    prompt: "How do you decide how much to spend on travel?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-seasons",
    prompt: "What is the best season to travel, in your opinion?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-photos",
    prompt: "How many photos do you take on a trip, and what do you do with them later?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-companions",
    prompt: "What makes someone a good travel companion?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-jet-lag",
    prompt: "How do you deal with jet lag after a long flight?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-day-trips",
    prompt: "Describe a perfect day trip from where you live.",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-fears",
    prompt: "What is something about traveling that makes you nervous?",
    category: "travel",
    difficulty: "challenge",
  },
  {
    id: "travel-hometown-tour",
    prompt: "If a friend visited your hometown, where would you take them?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-tourist",
    prompt: "Do you prefer guided tours or exploring on your own?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-habits-grown",
    prompt: "How has your travel style changed compared to a few years ago?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "travel-where-next",
    prompt: "Where is the next place you want to visit, and what would you do there?",
    category: "travel",
    difficulty: "easy",
  },
  {
    id: "travel-travel-books",
    prompt: "Do you read about a place before you visit it, or discover it when you arrive?",
    category: "travel",
    difficulty: "medium",
  },
  {
    id: "creativity-inspiration",
    prompt: "Where do you usually find inspiration?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-block",
    prompt: "What do you do when you feel creatively stuck?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-hobby",
    prompt: "Describe a creative hobby you have or would like to start.",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-writing",
    prompt: "If you wrote a book, what would it be about?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-making",
    prompt: "Describe something you made by hand and how it turned out.",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-space",
    prompt: "What does your ideal creative space look like?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-play",
    prompt: "When was the last time you played something just for fun?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-ideas",
    prompt: "Where do your best ideas usually come from?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-taste",
    prompt: "Is good taste something you are born with or something you develop?",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-at-work",
    prompt: "How do you stay creative in a routine job?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-improvise",
    prompt: "Describe a time you had to improvise and it worked out.",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-observe",
    prompt: "What details do you notice in a busy street that others miss?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-daydream",
    prompt: "Where does your mind go when you daydream?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-projects",
    prompt: "Describe a creative project you finished and are proud of.",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-collaborate",
    prompt: "Do you create better alone or with other people?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-originality",
    prompt: "Does everything creative come from something that already exists?",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-failure",
    prompt: "Describe a creative attempt that failed and what you learned from it.",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-redesign",
    prompt: "If you could redesign any everyday object, what would you change about it?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-imagination",
    prompt: "How creative is your imagination compared to when you were a child?",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-finish",
    prompt: "Are you better at starting things or finishing them?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-music",
    prompt: "What song or piece of art makes you feel something every time you experience it?",
    category: "creativity",
    difficulty: "easy",
  },
  {
    id: "creativity-ordinary-art",
    prompt: "What is something ordinary that you think is actually beautiful?",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "creativity-invention",
    prompt: "Invent something useful for everyday life and explain how it works.",
    category: "creativity",
    difficulty: "challenge",
  },
  {
    id: "creativity-story",
    prompt: "Make up a short story that starts with this sentence: 'The door was already open.'",
    category: "creativity",
    difficulty: "medium",
  },
  {
    id: "hypothetical-superpower-choice",
    prompt: "If you could have one superpower, what would it be and why?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-time-travel-visit",
    prompt: "If you could travel in time, would you visit the past or the future?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-invisible",
    prompt: "If you were invisible for a day, what would you actually do?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-planet",
    prompt: "Describe what a new planet you just discovered might be like.",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-animals-talk",
    prompt: "If animals could talk, which animal would have the most interesting opinions?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-infinite-money",
    prompt: "If money were no object, how would you spend your days?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-one-wish-guaranteed",
    prompt: "What would you wish for if you had one guaranteed wish?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-swap-life",
    prompt: "Whose life would you trade places with for a week, and why?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-redo-day",
    prompt: "Which day of your life would you choose to live again, and what would you change?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-younger-self",
    prompt: "What advice would your current self give to you at fifteen?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-no-internet",
    prompt: "What would your life look like with no internet for a whole year?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-forever",
    prompt: "If you could live forever, what would you do with the extra time?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-teleport",
    prompt: "If teleportation existed, how would it change daily life?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-erase-memory",
    prompt: "If you could erase one memory, would you? Which one?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-robot-friend",
    prompt: "If a robot could perfectly simulate friendship, would you accept it as a friend?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-taller",
    prompt: "If you could change one thing about your physical appearance instantly, what would it be?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-start-over",
    prompt: "If you could restart your life at any age, would you?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-change-law",
    prompt: "If you could change one law tomorrow, what would you change and why?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-omniscience",
    prompt: "If you knew the answer to one question, what would you ask?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-extra-sense",
    prompt: "Which additional sense would you add to the human body if you could?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-language",
    prompt: "If everyone shared one language, what would be lost and what would be gained?",
    category: "hypothetical",
    difficulty: "challenge",
  },
  {
    id: "hypothetical-greatest-invention",
    prompt: "What is the greatest invention in history, in your opinion?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "hypothetical-worst-superpower",
    prompt: "What would be the most useless superpower, and how would you still use it?",
    category: "hypothetical",
    difficulty: "easy",
  },
  {
    id: "hypothetical-ghost",
    prompt: "If ghosts were real, would you want to meet one?",
    category: "hypothetical",
    difficulty: "medium",
  },
  {
    id: "situational-restaurant-order",
    prompt: "Your restaurant order arrives wrong. What do you say and do?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-lost-city",
    prompt: "You are lost in an unfamiliar city with no phone battery. What do you do?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-late",
    prompt: "You are running late to something important. Walk through what you do.",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-interview",
    prompt: "You are about to walk into a job interview. Describe your preparation and the moment you sit down.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-awkward-silence",
    prompt: "The conversation has gone silent. How do you break the silence?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-surprise-guest",
    prompt: "An unexpected guest rings your doorbell while your home is a mess. What happens?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-power-outage",
    prompt: "Describe how you would spend an evening with no electricity.",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-broken-phone",
    prompt: "Your phone breaks right before an important call. How do you handle it?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-wrong-gift",
    prompt: "You receive a gift you genuinely do not like. What do you say?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-missed-flight",
    prompt: "You miss your flight by ten minutes. What do you do next?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-spill",
    prompt: "You spill a drink on someone at a party. Walk through the whole moment.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-cold-call",
    prompt: "Describe how you would handle an unsolicited sales call.",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-locked-out",
    prompt: "You are locked out of your home with no spare key. What are your options?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-impromptu-speech",
    prompt: "You are asked to say a few words at an event with no warning. What do you say?",
    category: "situational",
    difficulty: "challenge",
  },
  {
    id: "situational-emergency",
    prompt: "You witness a minor accident on the street. Describe what you do.",
    category: "situational",
    difficulty: "challenge",
  },
  {
    id: "situational-first-meeting",
    prompt: "You are meeting your partner's parents for the first time. Walk through the visit.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-queue-jumper",
    prompt: "Someone jumps the queue in front of you. How do you respond?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-text-misread",
    prompt: "You realize you misread a text message and responded the wrong way. What now?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-taxi",
    prompt: "The taxi driver takes a wrong turn. What do you say?",
    category: "situational",
    difficulty: "easy",
  },
  {
    id: "situational-party-alone",
    prompt: "You arrive at a party and know no one. How do you spend the first half hour?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-return-item",
    prompt: "You need to return an item with a torn receipt. How do you handle the conversation?",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "situational-meeting-timing",
    prompt: "Your meeting ends at the exact moment you need to leave. How do you handle it?",
    category: "situational",
    difficulty: "challenge",
  },
  {
    id: "situational-help-stranger",
    prompt: "A stranger on the street asks you for help. Describe how you decide what to do.",
    category: "situational",
    difficulty: "challenge",
  },
  {
    id: "situational-wrong-door",
    prompt: "You walk into the wrong room during an event. Describe the moment.",
    category: "situational",
    difficulty: "medium",
  },
  {
    id: "fun-celebrity-dinner",
    prompt: "Which three people, alive or dead, would you invite to a dinner party?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-celebrity-pet",
    prompt: "If your pet became famous, what would it be famous for?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-superstition",
    prompt: "Which superstition do you secretly follow?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-useless-talent",
    prompt: "What is a completely useless talent you have?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-dream-home-design",
    prompt: "Describe your dream home in detail.",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-weird-combo",
    prompt: "What is a food combination you love that others find strange?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-game-show",
    prompt: "Which game show would you excel at, and why?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-embarrassing-moment",
    prompt: "Tell the story of your most embarrassing moment, in as much detail as you dare.",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-world-record",
    prompt: "What world record would you like to hold?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-breakfast-champion",
    prompt: "Design the ultimate breakfast and describe it.",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-board-game",
    prompt: "Which board game best reveals a person's true personality?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-unusual-job",
    prompt: "What is the strangest job you can imagine someone actually having?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-laughter",
    prompt: "What has made you laugh the hardest recently?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-invention-wacky",
    prompt: "Invent a ridiculous gadget and explain why everyone needs it.",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-karaoke",
    prompt: "What song would you confidently sing at karaoke?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-cartoon-life",
    prompt: "If you lived in a cartoon, which cartoon rules would apply to you?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-childhood-obsession",
    prompt: "What were you obsessed with as a child?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-future-laugh",
    prompt: "What do you think people will look back on and laugh about in fifty years?",
    category: "fun",
    difficulty: "challenge",
  },
  {
    id: "fun-pet-name",
    prompt: "If you adopted a pet today, what would you name it and why?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-desert-island",
    prompt: "You are stranded on a desert island with one item and one book. What do you choose?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-time-capsule",
    prompt: "What would you put in a time capsule to explain life today?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-joke",
    prompt: "Tell a joke you find genuinely funny and explain why it works.",
    category: "fun",
    difficulty: "challenge",
  },
  {
    id: "fun-celebrity-job",
    prompt: "Which celebrity would make the worst roommate, and why?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-hidden-talent-friend",
    prompt: "What hidden talent do you suspect your best friend has?",
    category: "fun",
    difficulty: "medium",
  },
  {
    id: "fun-everything-color",
    prompt: "If you had to pick one color to live with forever, what would it be?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-signature-snack",
    prompt: "What is the snack you are best known for making?",
    category: "fun",
    difficulty: "easy",
  },
  {
    id: "fun-dance",
    prompt: "What song makes you dance even in public?",
    category: "fun",
    difficulty: "medium",
  },
];
